version: '3'
services:
  storage:
    build: ./docker/storage
    container_name: pomodoro-storage
    image: pomodoro-storage
    volumes:
      - db:/var/lib/mysql

  db:
    build: ./docker/db
    container_name: pomodoro-db
    image: pomodoro-db
    environment:
      - MYSQL_DATABASE=pomodoro_development
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - storage
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: DockerfileRails
    environment:
      RAILS_ENV: development
    container_name: pomodoro-app
    image: pomodoro-app
    env_file:
      - .env
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/pomodoro
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

  web:
    build: ./docker/nginx
    container_name: pomodoro-web
    image: pomodoro-web
    env_file:
      - ./docker/nginx/.env
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/src:/usr/local/openresty/nginx/src
      - ./docker/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  db:
