version: '3'
services:
  storage:
    build: ./storage
    container_name: pomodoro-storage
    image: pomodoro-storage
    volumes:
      - db:/var/lib/mysql

  db:
    build: ./db
    container_name: pomodoro-db
    image: pomodoro-db
    environment:
      - MYSQL_DATABASE=pomodoro_development
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - storage
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/pomodoro
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - rails

volumes:
  db:
