version: '3'
services:
  storage:
    build: ./docker/storage
    container_name: pomodoro-storage
    image: pomodoro-storage
    volumes:
      - db:/var/lib/mysql

  db:
    build: ./docker/db
    container_name: pomodoro-db
    image: pomodoro-db
    environment:
      - MYSQL_DATABASE=pomodoro_development
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - storage
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: DockerfileRails
    environment:
      RAILS_ENV: development
    container_name: pomodoro-app
    image: pomodoro-app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/pomodoro
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

  web:
    build: ./nginx
    container_name: pomodoro-web
    image: pomodoro-web
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  db:
