
default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 3
  host: db
  database: pomodoro
  username: root
  password: ''

development:
  <<: *default
  database: pomodoro_development

test:
  <<: *default
  database: pomodoro_test

staging:
  <<: *default
  database: pomodoro_staging

production:
  <<: *default
  database: pomodoro_production
